name: CI

on:
  pull_request:
    branches: main

concurrency:
  group: static-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Run CI pipeline

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          version: "0.11.3"
          enable-cache: true

      - name: Install project and dependencies
        run: uv pip install --system ".[dev, solver-apis]"

      - name: Lint with Ruff
        # Will FAIL if any unfixable lint rule is violated
        run: ruff check --fix --show-fixes --output-format=github

      - name: Format with Ruff
        run: ruff format

      - name: Commit and push file changes from Ruff
        run: |
          git add '**/*.py'
          if ! git diff --staged --quiet; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -m "[Automated] Formatted with Ruff"
            git push origin "HEAD:${{ github.head_ref }}" --force
          fi

      - name: Check that docs can be built + Lint python docstrings with numpydoc (through Sphinx)
        # Will FAIL if Sphinx throws any warnings/errors or if any numpydoc lint rule is violated
        run: |
            make -C docs clean html
            rm -rf docs/source/auto_api/* docs/source/auto_examples/*

      - name: Static type check with mypy
        # Will FAIL if any error is found
        run: mypy src

      - name: Generate coverage report from unit tests
        # Will FAIL if measured coverage is below 100%
        run: pytest tests/unit_tests/ --no-summary --cov-report=xml --cov-fail-under 100

      - name: Generate badge file from coverage report
        run: |
          uv pip install --system genbadge[coverage]
          genbadge coverage -i coverage.xml -o coverage.svg

      - name: Commit and push badge file change
        run: |
          git add coverage.svg
          if ! git diff --staged --quiet; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -m "[Automated] Updated coverage badge"
            git push origin "HEAD:${{ github.head_ref }}" --force
          fi
