name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to PyPI on release

    if: github.repository_owner == 'samarthmistry' && startsWith(github.ref, 'refs/tags')

    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://pypi.org/p/opti-extensions

    permissions:
      id-token: write

    steps:
      - name: Check out repository and fetch all history for all branches & tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Build and validate package distributions
        run: |
          python -m pip install --upgrade build twine wheel
          python -m build --sdist --wheel
          twine check --strict dist/*

      - name: Upload package distributions on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
